### PR TITLE
Remove pullapprove and CI from review process

### LINKED ISSUE #8: Not using PullApprove
https://github.com/bndn/scrum/blob/master/README.md#reviewing

``` md
The review process is managed by PullApprove and its purpose is to improve the quality and correctness of the code. In addition to checking that all automated checks pass, 
```

We neither use PullApprove or automatic continuous integration, as ITU GitHub is limited :(

### PR DESCRIPTION
**Pull request by MGApcDev**
Closes #8

### CODE REVIEW

**Comment by kasperisager** [comment]
Looks good! Just needs approval from the Scrum master :smile:

**Comment by MGApcDev** [comment]
Oh right, I'll see if I can get a hold of him.

**Comment by MGApcDev** [comment]
Looks good Approved

**Comment by MGApcDev** [comment]
Approved looks good

[Approved with PullApprove](https://pullapprove.com/bndn/scrum/pull-request/9/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=bndn/scrum)

**Pull request merged**
